<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DSD.Common\DSD.Common.csproj" />
    <ProjectReference Include="..\DSD.Outbound\DSD.Outbound.csproj" />
  </ItemGroup>

</Project>
